import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ClerkProvider } from '@clerk/nextjs';

import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html
                lang='en'
                className='scroll-smooth antialiased'
                suppressHydrationWarning
            >
                <body className={`flex min-h-screen flex-col ${inter.className}`}>
                        <main className='grow'>{children}</main>
                </body>
            </html>
        </ClerkProvider>
    );
}